PyArray.__tojava__(): Reduce the coercion eagerness of arrays. This change is backward incompatible. It prevents the coercion of an entire array, just because the elements of the array can be coerced.
Example:

With a java method like:

   foo(double[] arr);

the python code
   a = jarray.zeros(10, "f") # an array of floats
   foo(a)

would succeed, but any changes to the array that foo might
perform would not be reflected back into the "a" object.

With this patch the example will fail with:

  TypeError: foo(): 1st arg can't be coerced to double[]

--HG--
extra : convert_revision : svn%3A79b11f02-f210-0410-99aa-fb189b3d1ac4/jython/trunk%40984