__call__(PyObject[], String[]): raise a TypeError instead of an AttributeError for closer conformance with CPython.  The error message is slightly different but that's unimportant.  E.g.
JPython 1.1beta2 on java1.2.1
Copyright (C) 1997-1999 Corporation for National Research Initiatives
>>> None()
Traceback (innermost last):
  File "<console>", line 1, in ?
TypeError: call of non-function ('None' object)


Python 1.5.2 (#7, Apr 16 1999, 18:24:22)  [GCC 2.8.1] on sunos5
Copyright 1991-1995 Stichting Mathematisch Centrum, Amsterdam
>>> None()
Traceback (innermost last):
  File "<stdin>", line 1, in ?
TypeError: call of non-function (type None)

--HG--
extra : convert_revision : svn%3A79b11f02-f210-0410-99aa-fb189b3d1ac4/jython/trunk%40727